logging:
  level:
    com.sw.mapper: debug
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/blog_mybatisplus?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8